### ISSUE TITLE
Missing osgi.service capability

### ISSUE THREAD

**Issue by amitjoy** [jupnp/jupnp#116]
The latest version of JUPnP doesn't provide the **_osgi.service_** capability for the following service.

1. org.jupnp.UpnpService

**Comment by kaikreuzer** [comment]
I would claim that [it does](https://github.com/jupnp/jupnp/blob/master/bundles/org.jupnp/META-INF/MANIFEST.MF#L78-L79).
Make sure that you use [release 2.5.2](https://github.com/jupnp/jupnp/releases/tag/2.5.2).

**Comment by maggu2810** [comment]
It has been added by #115 already.
