### ISSUE TITLE
Jetty is not configured to listen on any port

### ISSUE THREAD

**Issue by peterbuki** [jupnp/jupnp#119]
Jetty is not listening on any port, even if service is configured with ports specified:
`
new UpnpServiceImpl(new DefaultUpnpServiceConfiguration(8081, 8082));
`

This causing the devices failing to get the service descriptors.
As a quick fix modified JettyServletContainer:resetServer to specify the port:
`
        server = new Server(8081); // Has its own QueuedThreadPool
`

And Jetty started serving the descriptor files. 

Modifying the JettyServletContainer:addConnector seems to be a long-term solution, since the port is only available in this method:
`
        ServerConnector http = new ServerConnector(server);
        http.setHost(host);
        http.setPort(port);
        server.addConnector(http);
`

**Comment by n0y** [comment]
Fixing this issue would mean:

add `server.addConnector(new ServerConnector(server));` to `JettyServletContainer#addConnector`

And for supporting an ephemeral port as well:

First add a method `getLocalPort()` to `JettyServletContainer` with 
`
return Arrays.stream(server.getConnectors())
   .filter(conn -> conn instanceof ServerConnector)
   .map(conn -> (ServerConnector) conn)
   .map(ServerConnector::getLocalPort)
   .findAny()
   .orElse(port);
`
then define the method in the interface `ServletContainerAdapter`

then make `ServletStreamServerImpl#getPort` return `getConfiguration().getServletContainerAdapter().getLocalPort()`.

But when thinking about that:
* It should be able to listen on multiple interfaces
* and the sent datagrams should publish the right (routable) endpoints

This all seems a bit messed up to me. Apart from this quick fix that should be refactored...
