### ISSUE TITLE
Proper documentation required - For simple port forwarding

### ISSUE THREAD

**Issue by SangameswaranRS** [jupnp/jupnp#140]
A documentation would be helpful.

I'm starting uPnP client, attaching listeners.

to request port forward, I need a service instance, where do I get it? (OnRemoteDeviceAdded) is not at alll called

**Comment by kaikreuzer** [comment]
Documentation is available in https://github.com/jupnp/jupnp/tree/main/docs.
It might not be up to date, so please feel free to create PRs with improvements for it.

**Comment by ferriarnus** [comment]
I second this. The documentation isn't really clear, I can't find anything (but that can be me). I want to just be able to do a port forwarding when the software runs, and undo it when it stops. But I can't find any hints for this.
