### ISSUE TITLE
DatagramProcessorImpl trace null char

### ISSUE THREAD

**Issue by SurfaceS** [jupnp/jupnp#141]
`DatagramProcessorImpl` trace null char as it log the `DatagramPacket` buffer directly.
Adding **`trim()`** to the newly created String will solve that.

                log.trace("===================================== DATAGRAM BEGIN ============================================");
                log.trace(new String(datagram.getData()).trim());
                log.trace("-===================================== DATAGRAM END =============================================");

**Comment by wborn** [comment]
Does it mess up the logging somehow or does it only result in a strange character?

**Comment by wborn** [comment]
It is still unclear what kind of issue this would fix.
