### ISSUE TITLE
UpnpServiceImpl.start() does a search before we can add any registry listener

### ISSUE THREAD

**Issue by ijabz** [jupnp/jupnp#145]
In `UpnpServiceImpl.startup()` we have
 
```
 if (isInitialSearchEnabled) {
   controlPoint.search(new STAllHeader());
 }

```
to initiate a search, `isInitialSearchEnabled `defaults to true but there is no way to set it false so start always a does a search

We can only add a registry listener with

`upnpService.getRegistry().addListener(upnpListener);
`
But registry is not initialized until `startup()` ran, so therefore impossible to register registry listeners until after done a search

(Note cling project that this is forked from works slightly differently, able to set registry listeners beforehand)

**Comment by wborn** [comment]
There seems to be a [UpnpServiceConfig.xml](https://github.com/jupnp/jupnp/blob/4a3ab9dec37cb9be324d02f6dc81ffca74237e1e/bundles/org.jupnp/OSGI-INF/metatype/UpnpServiceConfig.xml) for this which is not used for reasons unknown. I added an `activate` method that uses the config while migrating the XML file to be generated using DS annotations in #155.
