### ISSUE TITLE
Where is the org.jupnp.android.AndroidUpnpServiceConfiguration ?

### ISSUE THREAD

**Issue by courville** [jupnp/jupnp#153]
Context: I am trying to migrate from cling to jupnp for my Android open-source video player application.
I used to rely on:
```
cling/core/src/main/java/org/fourthline/cling/android/AndroidUpnpServiceConfiguration.java
cling/core/src/main/java/org/fourthline/cling/android/AndroidUpnpServiceImpl.java
cling/core/src/main/java/org/fourthline/cling/android/AndroidUpnpService.java
```
which does not exist in jupnp even if it is reference in the doc https://github.com/jupnp/jupnp/blob/main/docs/android/index.xhtml and in the code:
```
protected DefaultUpnpServiceConfiguration(int streamListenPort, int multicastResponsePort, boolean checkRuntime) {
        if (checkRuntime && ModelUtil.ANDROID_RUNTIME) {
            throw new Error("Unsupported runtime environment, use org.jupnp.android.AndroidUpnpServiceConfiguration");
        }
```
Is there a plan to reintroduce these for easier usage under Android so that it will spare others facing the issue of readapting it themselves (cf. https://github.com/jupnp/jupnp/issues/148, https://github.com/jupnp/jupnp/issues/107)?

**Comment by wborn** [comment]
Looks like all the Android code got removed with the initial scope reduction: https://github.com/jupnp/jupnp/commit/1d729774a71019f3f15a54eda3fcb7c9f3bf9c96
So the (Java) docs were never updated for this.
Do you think it makes sense to also support Android @kaikreuzer?

**Comment by kaikreuzer** [comment]
> Do you think it makes sense to also support Android @kaikreuzer?

In general, it would of course be nice - but we would need a maintainer that uses it on Android and makes sure it is usable there. Not sure if anybody volunteers for this...

**Comment by courville** [comment]
@kaikreuzer, sorry for the late answer. My proposal would be to add it back and I can test if it is working in my android application https://github.com/nova-video-player/aos-AVP (which is not universal).
To be clear, I would not be the maintainer of this part of the code.

**Comment by courville** [comment]
> I'm fine with adding the classes back if you can check that this allows for making jupnp usable on Android.

Good news: I will provide feedback in this issue on my progress once added back.

**Comment by courville** [comment]
@wborn, I see a spike of activities on jupnp. Please ping me when Android classed are added back so that I can proceed and provide feedback on the Android usability (at least in my app as client).

**Comment by courville** [comment]
@wborn, thanks, I integrated your jupnp branch with Android support in place of cling.
Strangely I had to manually start the service in my UpnpManager:
```
            mAndroidUpnpService = (AndroidUpnpService) service;
            mAndroidUpnpService.get().startup();
            mAndroidUpnpService.getRegistry().addListener(mRegistryListener);
```
and before with cling a simple `mAndroidUpnpService.getRegistry().addListener(mRegistryListener);` was enough.
But when I do this, I get lots of:
```
2024-01-24 12:30:26.668 25533-25684 org.jupnp....escriptors org.courville.nova                   W  Could not hydrate device or its services from descriptor: (RemoteDevice) Identity: (RemoteDeviceIdentity) UDN: uuid:001132d1-98a7-0011-a798-a798d1321100, Descriptor: http://192.168.0.10:50001/desc/device.xml, Root: true
                                                                                                    org.jupnp.binding.xml.DescriptorBindingException: Could not parse device descriptor
                                                                                                    	at org.jupnp.binding.xml.UDA10DeviceDescriptorBinderImpl.describe(UDA10DeviceDescriptorBinderImpl.java:110)
                                                                                                    	at org.jupnp.binding.xml.RecoveringUDA10DeviceDescriptorBinderImpl.describe(RecoveringUDA10DeviceDescriptorBinderImpl.java:54)
                                                                                                    	at org.jupnp.protocol.RetrieveRemoteDescriptors.describe(RetrieveRemoteDescriptors.java:187)
                                                                                                    	at org.jupnp.protocol.RetrieveRemoteDescriptors.describe(RetrieveRemoteDescriptors.java:175)
                                                                                                    	at org.jupnp.protocol.RetrieveRemoteDescriptors.run(RetrieveRemoteDescriptors.java:106)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:920)
                                                                                                    Caused by: java.lang.IllegalArgumentException: http://apache.org/xml/properties/locale
                                                                                                    	at org.apache.harmony.xml.parsers.DocumentBuilderFactoryImpl.setAttribute(DocumentBuilderFactoryImpl.java:86)
                                                                                                    	at org.jupnp.binding.xml.UDA10DeviceDescriptorBinderImpl.describe(UDA10DeviceDescriptorBinderImpl.java:96)
                                                                                                    	... 7 common frames omitted
```
though a curl on `http://192.168.0.10:50001/desc/device.xml` gives:
```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<root xmlns="urn:schemas-upnp-org:device-1-0">
<specVersion>
<major>1</major>
<minor>0</minor>
</specVersion>
<device>
<deviceType>urn:schemas-upnp-org:device:MediaServer:1</deviceType>
<friendlyName>ds720p</friendlyName>
<manufacturer>Synology Inc.</manufacturer>
<manufacturerURL>http://www.synology.com/</manufacturerURL>
<modelName>DS720+</modelName>
<modelDescription>Synology DLNA/UPnP Media Server</modelDescription>
<modelURL>http://www.synology.com</modelURL>
<serialNumber>2060QWR0MB46B</serialNumber>
<UDN>uuid:001132d1-98a7-0011-a798-a798d1321100</UDN>
<presentationURL>http://192.168.0.10:5000/</presentationURL>
<iconList>
<icon>
<mimetype>image/jpeg</mimetype>
<width>120</width>
<height>120</height>
<depth>24</depth>
<url>/tmp_icon/dmsicon120.jpg</url>
</icon>
<icon>
<mimetype>image/jpeg</mimetype>
<width>48</width>
<height>48</height>
<depth>24</depth>
<url>/tmp_icon/dmsicon48.jpg</url>
</icon>
<icon>
<mimetype>image/png</mimetype>
<width>120</width>
<height>120</height>
<depth>24</depth>
<url>/tmp_icon/dmsicon120.png</url>
</icon>
<icon>
<mimetype>image/png</mimetype>
<width>48</width>
<height>48</height>
<depth>24</depth>
<url>/tmp_icon/dmsicon48.png</url>
</icon>
</iconList>
<serviceList>
<service>
<serviceType>urn:schemas-upnp-org:service:ConnectionManager:1</serviceType>
<serviceId>urn:upnp-org:serviceId:ConnectionManager</serviceId>
<SCPDURL>/connmgrSCPD.xml</SCPDURL>
<controlURL>/ConnectionManager/control</controlURL>
<eventSubURL>/ConnectionManager/event</eventSubURL>
</service>
<service>
<serviceType>urn:schemas-upnp-org:service:ContentDirectory:1</serviceType>
<serviceId>urn:upnp-org:serviceId:ContentDirectory</serviceId>
<SCPDURL>/cdsxSCPD.xml</SCPDURL>
<controlURL>/ContentDirectory/control</controlURL>
<eventSubURL>/ContentDirectory/event</eventSubURL>
</service>
<service>
<serviceType>urn:microsoft.com:service:X_MS_MediaReceiverRegistrar:1</serviceType>
<serviceId>urn:microsoft.com:serviceId:X_MS_MediaReceiverRegistrar</serviceId>
<SCPDURL>/msrrSCPD.xml</SCPDURL>
<eventSubURL>/MediaReceiverRegistrar/event</eventSubURL>
<controlURL>/MediaReceiverRegistrar/control</controlURL>
</service>
</serviceList>
</device>
</root>
```
I just wanted to report quickly progress.
I will dig further.

**Comment by wborn** [comment]
Thanks for giving it a test. There were a few missing classes I ran into while adding the Android code back. I wasn't too sure if they were really needed for Android support.

The classes instantiated here are still missing:

https://github.com/4thline/cling/blob/0ca10d5e73bdc8062eeffad57d67dd8ee260379c/core/src/main/java/org/fourthline/cling/android/AndroidUpnpServiceConfiguration.java#L123-L136

I'll try to add those classes back too on my branch and then maybe you can give it another try.

**Comment by wborn** [comment]
>   Caused by: java.lang.IllegalArgumentException: http://apache.org/xml/properties/locale
>   	at org.apache.harmony.xml.parsers.DocumentBuilderFactoryImpl.setAttribute(DocumentBuilderFactoryImpl.java:86)

Perhaps it uses another parser on Android which doesn't support this attribute. It was only recently set with https://github.com/jupnp/jupnp/pull/158. Does it work better if you catch the IllegalArgumentException or comment the line @courville?

**Comment by courville** [comment]
> Perhaps it uses another parser on Android which doesn't support this attribute. It was only recently set with #158. Does it work better if you catch the IllegalArgumentException or comment the line @courville?

Nice: I confirm that commenting the line makes my UPnP shares browsable.

**Comment by wborn** [comment]
Nice to see it's starting to work! :slightly_smiling_face: 
I've rebased the branch and added a commit to catch the IAE when setting the attribute.
Let me know if it all properly works and I'll then create a PR for it.

**Comment by courville** [comment]
@wborn, just resynced to your branch and it properly works on my side thanks.
I will publish a pre-release of the app and ask UPnP heavy users to give it a shot when your PR goes through.
Thanks for the help and support.

**Comment by courville** [comment]
FTR, my application is targeting `minSdkVersion 21` (Android 5/L) and thus I cannot go above `org.eclipse.jetty` version 9.3.14 otherwise I need to bump to `minSdkVersion 26` (Android 8/O) since it complains about:
```
MethodHandle.invoke and MethodHandle.invokeExact are only supported starting with Android O (--min-api 26): Lorg/eclipse/jetty/servlet/DecoratingListener$DynamicDecorator;decorate(Ljava/lang/Object;)Ljava/lang/Object;
```
As a consequence I have this in my `build.gradle` (until proper jupnp release):
```
    api files('libs/jupnp.jar')
    api files('libs/jupnp-android.jar')
    api files('libs/jupnp-support.jar')
    implementation group: 'org.eclipse.jetty', name: 'jetty-server', version:'9.4.14.v20181114'
    implementation group: 'org.eclipse.jetty', name: 'jetty-servlet', version:'9.4.14.v20181114'
    implementation group: 'org.eclipse.jetty', name: 'jetty-client', version:'9.4.14.v20181114'
    implementation 'javax.servlet:javax.servlet-api:4.0.1'
```
I do not know if this is a problem moving forward.

**Comment by wborn** [comment]
As long as the class names and method signatures stay the same you can probably keep using the older Jetty version.

**Comment by courville** [comment]
Note that for Android, to get proper release, I had to add the following rules in my `proguard-project.txt`:
```
-dontwarn org.osgi.framework.**
-dontwarn org.osgi.service.**
```

**Comment by courville** [comment]
When do you plan to have a proper jupnp release including the under review PR?

**Comment by wborn** [comment]
I think it would be nice to create a 3.0.0 release when all open PRs are merged. That way we can get some more feedback on all changes. WDYT @kaikreuzer?

**Comment by courville** [comment]
Here we go: https://github.com/nova-video-player/aos-AVP/releases/tag/v6.2.56 published and based on jupnp to collect feedback from users.

**Comment by courville** [comment]
Great thanks for the support and the PR merge.
@kaikreuzer, any release planned soon?

**Comment by kaikreuzer** [comment]
Sure, if @wborn is done with the stream of refactoring PRs, we can certainly do a new release in the next days.

**Comment by wborn** [comment]
Many thanks for reviewing my endless stream of PRs @kaikreuzer . 👍 I'm done with it for now, so if you can make a 3.0.0 release some day soon that would be great!

**Comment by courville** [comment]
Err... sorry for the noise wrong cut and paste

**Comment by courville** [comment]
@kaikreuzer, I am eager to deploy the upcoming release in my app: any ETA on new release?

**Comment by kaikreuzer** [comment]
It has just been released! https://github.com/jupnp/jupnp/releases/tag/3.0.0

**Comment by courville** [comment]
@kaikreuzer and @wborn thanks for your support. New Nova Video Player release made using jupnp https://github.com/nova-video-player/aos-AVP/releases/tag/v6.2.63
See https://github.com/nova-video-player/aos-MediaLib/commit/57a3d0ed871efcd1d7be8001381c85135146c9f3
