### ISSUE TITLE
Potential garbled bug

### ISSUE THREAD

**Issue by tesshucom** [jupnp/jupnp#160]
Hello, thanks for this useful software !

I am developing a Airsonic fork. A version compatible with Java21 + Spring Boot 3.2 will be released soon. I decided to take this opportunity to migrate UPnP from Cling to jupnp. There are almost no problems, but I was concerned about one problem with garbled characters.

For now, the problem has been avoided by creating a derived class without using HttpExchangeUpnpStream.

#### Cause location

There seems to be a problem with UpnpMessage#getBodyBytes.

https://github.com/jupnp/jupnp/blob/0fcab2b577ae64b56c400398c49d4197d247d0f3/bundles/org.jupnp/src/main/java/org/jupnp/transport/impl/HttpExchangeUpnpStream.java#L130-L132

getBytes() takes no arguments. In other words, character encoding cannot be controlled in the source code.

https://github.com/jupnp/jupnp/blob/0fcab2b577ae64b56c400398c49d4197d247d0f3/bundles/org.jupnp/src/main/java/org/jupnp/model/message/UpnpMessage.java#L152-L165

 - [strange behaviour of java getBytes vs getBytes(charset)](https://stackoverflow.com/questions/31611857/strange-behaviour-of-java-getbytes-vs-getbytescharset)

#### Reproduce

Because it is platform dependent, it does not occur in every environment.

 - In JVM before Java18
 - If the default encoding is other than UTF-8
 - Use HttpExchangeUpnpStream

#### Proposed solution

I think there are various ways to respond depending on the policy... Since there are various smells in just a few lines, it might be a good idea to create a new override method. I think you can specify UTF-8 for Original. Because it is the same behavior without arguments in JVM since Java18.

```
    /**
     * Use {@link #getBodyBytes(Charset)}
     * @deprecated Not NullSafe (Effective Java)
     */
    @Deprecated
    public byte[] getBodyBytes() {
        try {
            if (!hasBody()) {
                return null;
            }
            if (getBodyType().equals(BodyType.STRING)) {
                return getBodyString().getBytes(StandardCharsets.UTF_8);
            } else {
                return (byte[]) getBody();
            }
        } catch (Exception ex) {
            throw new RuntimeException(ex);
        }
    }

    public byte[] getBodyBytes(Charset charset) {
        if (hasBody()) {
            if (getBodyType().equals(BodyType.STRING)) {
                return getBodyString().getBytes(charset);
            }
            return (byte[]) getBody();
        }
        return new byte[0];
    }
```

If there was an override function like the one above, the code for HttpExchangeUpnpStream shown at the beginning would have been written as follows. It seems redundant, but you can see right away that it will definitely work.

```
        byte[] responseBodyBytes = responseMessage.getBodyBytes(StandardCharsets.UTF_8);
        int contentLength = responseBodyBytes.length == 0 ? -1 : responseBodyBytes.length;
```

**Comment by wborn** [comment]
If I read the [protocol docs](https://openconnectivity.org/upnp-specs/UPnP-arch-DeviceArchitecture-v2.0-20200417.pdf) it looks like it should always use UTF-8. So in that case the fix is just to always use that. I see there is more code calling `getBytes()` on Strings without specifying the `Charset` so there may be more issues like this.

**Comment by tesshucom** [comment]
OK, We need a method that either replaces an existing method or takes no arguments and behaves correctly. In fact, even non-Latin countries do not use anything other than UTF-8 except in special cases. 
I was a little concerned about whether to replace it without backward compatibility (even if it's wrong). I think this has something to do with the project's policy, which is different from general theory.

Whatever the direction of this project, I'm confident it will be better than before 😉

**Comment by wborn** [comment]
The next version is a major version bump to 3.0.0 and it requires at least Java 11 instead of Java 7. So it can also have a few more breaking changes compared to 2.x. 😉

**Comment by wborn** [comment]
I had a closer look and saw that the `UpnpMessage` also has a `getContentTypeCharset()` method that gets the charset from the message header. So it is probably best to use that and if it is not set default to UTF-8. WDYT?

**Comment by tesshucom** [comment]
Ah, I hadn't thought about it too much, but it seems like an attractive idea. If the default was UTF-8, realistically no one would complain. (In other cases, if you can control it somehow.) As far as I know, I have never seen any mention of this in the old UPnP specifications, so I was thinking if it would conform to the general-purpose XML specifications. I'm not an expert.

When I searched, I found the following documents:

https://docs.osgi.org/specification/osgi.cmpn/7.0.0/service.upnp.html

> 111.10 Localization
> All values of the UPnP properties are obtained from the device using the device's default locale. If an application wants to query a set of localized property values, it has to use the method [getDescriptions(String)](https://docs.osgi.org/specification/osgi.cmpn/7.0.0/service.upnp.html#org.osgi.service.upnp.UPnPDevice.getDescriptions-String-). For localized versions of the icons, the method [getIcons(String)](https://docs.osgi.org/specification/osgi.cmpn/7.0.0/service.upnp.html#org.osgi.service.upnp.UPnPDevice.getIcons-String-) is to be used.

This is just an example, but... to be very precise, this kind of detailed rules may be defined in the DTD specifications used for communication. (So I don't think it's a big mistake to follow the existing properties that had been be implemented accordingly...? )
