### ISSUE TITLE
Documentation missing from website

### ISSUE THREAD

**Issue by wborn** [jupnp/jupnp#215]
It would be nice when the documentation in `docs` was published on the [website](https://www.jupnp.org/) so it can be more easily read.
It looks like previously the Maven Site Plug-in used the XHTML files when generating the website.

Did you already have some plans for the documentation @kaikreuzer?

Perhaps the docs are easier to read and maintain when they are converted to Markdown?

There are also many [`// DOC:` markers](https://github.com/search?q=repo%3Ajupnp%2Fjupnp+%22%2F%2F+DOC%3A%22&type=code) in the code which may be removed depending on how the documentation will be created. These markers seem to be only used by [Lemma](http://4thline.org/projects/lemma/manual/lemma-manual.xhtml).

The original Cling documentation is still available here:
http://4thline.org/projects/cling/core/manual/cling-core-manual.xhtml

**Comment by kaikreuzer** [comment]
> Did you already have some plans for the documentation @kaikreuzer?

No, I actually never really took care of that since forking cling... 🙄 

> Perhaps the docs are easier to read and maintain when they are converted to Markdown?

Yes, I agree.

**Comment by lolodomo** [comment]
Are the settings documented somewhere in documentation ?
I just added an OSGi setting to restrict network interfaces but I have no idea where to document that.

**Comment by wborn** [comment]
I found some docs for the existing System properties here:

https://github.com/jupnp/jupnp/blob/261787b3ad5b322c68baae4822150a14657b523b/docs/basicapi/upnpservice.xhtml#L140
