### ISSUE TITLE
Enable GitHub discussions

### ISSUE THREAD

**Issue by wborn** [jupnp/jupnp#222]
Maybe we should enable GitHub discussions so not every user question results in an issue @kaikreuzer? 

You can also convert issues into discussions:

https://docs.github.com/en/discussions/managing-discussions-for-your-community/moderating-discussions#converting-an-issue-to-a-discussion

**Comment by kaikreuzer** [comment]
Ok for me, although I think the activity of discussion groups might be fairly limited here - but why not.

**Comment by wborn** [comment]
Great! It's enabled now: https://github.com/jupnp/jupnp/discussions
Let's see how it goes. :slightly_smiling_face: 
I've already tested converting a few issues into discussions.
