### ISSUE TITLE
JUPNP Message Parsing Failure due to DocumentBuilder Namespace Reset on Android

### ISSUE THREAD

**Issue by norohind** [jupnp/jupnp#232]
I'm in the process of migrating [Dsub2000](https://github.com/paroj/DSub2000), a fork of [Dsub](https://github.com/daneren2005/Subsonic), from cling to jupnp library. I've encountered a problem when the jupnp starts failing message parsing after 20 parsed messages. 

I have put up [a minimal reproducible example](https://github.com/norohind/DSub2000/blob/27aa40e964362a3caae7ae858444a36d05b86ec1/app/src/androidTest/java/github/daneren2005/dsub/domain/JUPNPTest.java) in form of an instrumented test, it makes jupnp parse 20 xml messages, prints `--- Crash after this line ---` and calls *readBody* once again to capture the failure. Here's the log output of running this example when the problem occurs:
```
04-21 13:35:24.856 16154 16177 I System.out: --- Crash after this line ---
04-21 13:35:24.856 16154 16177 V ojts.SOAPActionProcesso: Reading body of github.daneren2005.dsub.domain.JUPNPTest$1@6cf33de for: (ActionInvocation) (Action, Arguments: 0) GetPositionInfo
04-21 13:35:24.856 16154 16177 V ojts.SOAPActionProcesso: ===================================== SOAP BODY BEGIN ============================================
04-21 13:35:24.856 16154 16177 I System.out: getBodyString
04-21 13:35:24.856 16154 16177 V ojts.SOAPActionProcesso: <?xml version="1.0" encoding="utf-8"?><s:Envelope s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body><u:GetPositionInfoResponse xmlns:u="urn:schemas-upnp-org:service:AVTransport:1"><Track>1</Track><TrackDuration>0</TrackDuration><TrackMetaData>doesn't really matter</TrackMetaData><TrackURI>doesn't really matter</TrackURI><RelTime>0:00:00</RelTime><AbsTime>0:00:00</AbsTime><RelCount>2147483647</RelCount><AbsCount>2147483647</AbsCount></u:GetPositionInfoResponse></s:Body></s:Envelope>
04-21 13:35:24.856 16154 16177 V ojts.SOAPActionProcesso: -===================================== SOAP BODY END ============================================
04-21 13:35:24.856 16154 16177 I System.out: IsBodyNonEmptyString
04-21 13:35:24.856 16154 16177 I System.out: getBodyString
04-21 13:35:24.858 16154 16177 E TestRunner: failed: testSetCreated(github.daneren2005.dsub.domain.JUPNPTest)
04-21 13:35:24.858 16154 16177 E TestRunner: ----- begin exception -----
04-21 13:35:24.860 16154 16177 E TestRunner: org.jupnp.model.UnsupportedDataException: Can't transform message payload
04-21 13:35:24.860 16154 16177 E TestRunner:    at org.jupnp.transport.impl.SOAPActionProcessorImpl.readBody(SOAPActionProcessorImpl.java:164)
04-21 13:35:24.860 16154 16177 E TestRunner:    at github.daneren2005.dsub.domain.JUPNPTest.testSetCreated(JUPNPTest.java:46)
04-21 13:35:24.860 16154 16177 E TestRunner:    at java.lang.reflect.Method.invoke(Native Method)
04-21 13:35:24.860 16154 16177 E TestRunner:    at junit.framework.TestCase.runTest(TestCase.java:168)
04-21 13:35:24.860 16154 16177 E TestRunner:    at junit.framework.TestCase.runBare(TestCase.java:134)
04-21 13:35:24.860 16154 16177 E TestRunner:    at junit.framework.TestResult$1.protect(TestResult.java:115)
04-21 13:35:24.860 16154 16177 E TestRunner:    at androidx.test.internal.runner.junit3.AndroidTestResult.runProtected(AndroidTestResult.java:73)
04-21 13:35:24.860 16154 16177 E TestRunner:    at junit.framework.TestResult.run(TestResult.java:118)
04-21 13:35:24.860 16154 16177 E TestRunner:    at androidx.test.internal.runner.junit3.AndroidTestResult.run(AndroidTestResult.java:51)
04-21 13:35:24.860 16154 16177 E TestRunner:    at junit.framework.TestCase.run(TestCase.java:124)
04-21 13:35:24.860 16154 16177 E TestRunner:    at androidx.test.internal.runner.junit3.NonLeakyTestSuite$NonLeakyTest.run(NonLeakyTestSuite.java:62)
04-21 13:35:24.860 16154 16177 E TestRunner:    at junit.framework.TestSuite.runTest(TestSuite.java:243)
04-21 13:35:24.860 16154 16177 E TestRunner:    at junit.framework.TestSuite.run(TestSuite.java:238)
04-21 13:35:24.860 16154 16177 E TestRunner:    at androidx.test.internal.runner.junit3.DelegatingTestSuite.run(DelegatingTestSuite.java:97)
04-21 13:35:24.860 16154 16177 E TestRunner:    at androidx.test.internal.runner.junit3.AndroidTestSuite.run(AndroidTestSuite.java:65)
04-21 13:35:24.860 16154 16177 E TestRunner:    at androidx.test.internal.runner.junit3.JUnit38ClassRunner.run(JUnit38ClassRunner.java:115)
04-21 13:35:24.860 16154 16177 E TestRunner:    at org.junit.runners.Suite.runChild(Suite.java:128)
04-21 13:35:24.860 16154 16177 E TestRunner:    at org.junit.runners.Suite.runChild(Suite.java:27)
04-21 13:35:24.860 16154 16177 E TestRunner:    at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
04-21 13:35:24.860 16154 16177 E TestRunner:    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
04-21 13:35:24.860 16154 16177 E TestRunner:    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
04-21 13:35:24.860 16154 16177 E TestRunner:    at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
04-21 13:35:24.860 16154 16177 E TestRunner:    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
04-21 13:35:24.860 16154 16177 E TestRunner:    at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
04-21 13:35:24.860 16154 16177 E TestRunner:    at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
04-21 13:35:24.860 16154 16177 E TestRunner:    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
04-21 13:35:24.860 16154 16177 E TestRunner:    at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
04-21 13:35:24.860 16154 16177 E TestRunner:    at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:67)
04-21 13:35:24.860 16154 16177 E TestRunner:    at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:58)
04-21 13:35:24.860 16154 16177 E TestRunner:    at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:446)
04-21 13:35:24.860 16154 16177 E TestRunner:    at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2402)
04-21 13:35:24.860 16154 16177 E TestRunner: Caused by: java.lang.RuntimeException: Response root element was not 'Envelope'
04-21 13:35:24.860 16154 16177 E TestRunner:    at org.jupnp.transport.impl.SOAPActionProcessorImpl.readBodyElement(SOAPActionProcessorImpl.java:232)
04-21 13:35:24.860 16154 16177 E TestRunner:    at org.jupnp.transport.impl.SOAPActionProcessorImpl.readBody(SOAPActionProcessorImpl.java:154)
04-21 13:35:24.860 16154 16177 E TestRunner:    ... 30 more
04-21 13:35:24.860 16154 16177 E TestRunner: ----- end exception -----
04-21 13:35:24.864 16154 16177 I TestRunner: finished: testSetCreated(github.daneren2005.dsub.domain.JUPNPTest)

org.jupnp.model.UnsupportedDataException: Can't transform message payload
at org.jupnp.transport.impl.SOAPActionProcessorImpl.readBody(SOAPActionProcessorImpl.java:164)
at github.daneren2005.dsub.domain.JUPNPTest.testSetCreated(JUPNPTest.java:46)
... 28 trimmed
Caused by: java.lang.RuntimeException: Response root element was not 'Envelope'
at org.jupnp.transport.impl.SOAPActionProcessorImpl.readBodyElement(SOAPActionProcessorImpl.java:232)
at org.jupnp.transport.impl.SOAPActionProcessorImpl.readBody(SOAPActionProcessorImpl.java:154)
... 30 more
```

## My investigation
Jupnp reuses a pre-created pool of platform specific implementation of `javax.xml.parsers.DocumentBuilder`, which are created with a platform specific implementation of `javax.xml.parsers.DocumentBuilderFactory`. An acquired *platform specific* instance of a factory method `.setNamespaceAware(true)` is being [called](https://github.com/jupnp/jupnp/blob/3.0.1/bundles/org.jupnp/src/main/java/org/jupnp/transport/impl/PooledXmlProcessor.java#L57). It tells the factory to create instances of `DocumentBuilder` which are *namespace aware*. After every use of an instance of `DocumentBuilder` and before returning it to the pool, the jupnp [calls](https://github.com/jupnp/jupnp/blob/3.0.1/bundles/org.jupnp/src/main/java/org/jupnp/transport/impl/PooledXmlProcessor.java#L136) a `.reset()` method on the instance. 

I have checked on my physical phone and an emulator, this *platform specific* implementation is `org.apache.harmony.xml.parsers`. In this particular implementation, on method `.reset()` it unconditionally sets internal flag `namespaceAware` of a specific instance to false.

Jupnp ends up putting this not anymore *namespace aware* `DocumentBuilder` back to pool. Eventually (after 20 message parsed messages, this is default pool size) not *namespace aware* builder parses a message and in [this condition](https://github.com/jupnp/jupnp/blob/main/bundles/org.jupnp/src/main/java/org/jupnp/transport/impl/SOAPActionProcessorImpl.java#L232) jupnp gets `s:Envelope` `getUnprefixedNodeName(envelopeElement)` as return value of the call and throws RuntimeException line below.

*Namespace awareness* is important, because it allows the parser to distinguish prefixes in xml tags, like prefix `s` and in tag `Envelope` in raw tag xml element `s:Envelope`.

In JDK17 it uses `com.sun.org.apache.xerces.internal.jaxp` implementation and that's work just fine and respects namespace awareness during `.reset()` call. 

Why it wasn't a problem with cling? Because this pool based mechanism was [introduced](https://github.com/jupnp/jupnp/commit/acc08768f2a18a17b1e221a7c7c12e80f7ab833c) exclusively to jupnp fork. 

I'm really not sure how this wasn't a problem for [aos-AVP](https://github.com/nova-video-player/aos-AVP/releases/tag/v6.2.63), https://github.com/nova-video-player/aos-AVP/issues/74, maybe i'm doing something wrong.

**Comment by wborn** [comment]
> I'm really not sure how this wasn't a problem for [aos-AVP](https://github.com/nova-video-player/aos-AVP/releases/tag/v6.2.63), https://github.com/nova-video-player/aos-AVP/issues/74, maybe i'm doing something wrong.

Do you also have this issue @courville?

The `DocumentBuilder` JavaDoc suggests it is a bug in your particular implementation:

```javadoc
    /**
     * <p>Reset this <code>DocumentBuilder</code> to its original configuration.</p>
     *
     * <p><code>DocumentBuilder</code> is reset to the same state as when it was created with
     * {@link DocumentBuilderFactory#newDocumentBuilder()}.
     * <code>reset()</code> is designed to allow the reuse of existing <code>DocumentBuilder</code>s
     * thus saving resources associated with the creation of new <code>DocumentBuilder</code>s.</p>
     *
     * <p>The reset <code>DocumentBuilder</code> is not guaranteed to have the same {@link EntityResolver} or {@link ErrorHandler}
     * <code>Object</code>s, e.g. {@link Object#equals(Object obj)}.  It is guaranteed to have a functionally equal
     * <code>EntityResolver</code> and <code>ErrorHandler</code>.</p>
     *
     * @throws UnsupportedOperationException When implementation does not
     *   override this method.
     *
     * @since 1.5
     */
    public void reset() {
```

A workaround could be to only return it to the pool if it is still namespace aware after the reset, e.g.:

```java
    private void returnBuilder(DocumentBuilder builder) throws FactoryConfigurationError, ParserConfigurationException {
        builder.reset();
        if (builder.isNamespaceAware()) {
            builderPool.add(builder);
        }
    }
```

**Comment by wborn** [comment]
> I have checked on my physical phone and an emulator, this platform specific implementation is org.apache.harmony.xml.parsers. In this particular implementation, on method .reset() it unconditionally sets internal flag namespaceAware of a specific instance to false.

What Android version are you using? 

https://en.wikipedia.org/wiki/Apache_Harmony#Use_in_Android_SDK:

> Android 7.0 "Nougat" replaced Harmony with OpenJDK.

**Comment by wborn** [comment]
Maybe they did not yet replace everything of Apache Harmony. If I read the reset() Android API docs it should behave differently compared to Java.

https://developer.android.com/reference/javax/xml/parsers/DocumentBuilder#reset()

> Reset this DocumentBuilder.
> 
> This method removes both the EntityResolver and ErrorHandler instances associated with this DocumentBuilder and sets all internal properties to false including those set by the DocumentBuilderFactory when this DocumentBuilder was created.

**Comment by norohind** [comment]
> sets all internal properties to false 
Ahh, now this makes sense.

I wonder if it's possibly to not call *reset()* as it just set all internal flags to false, given those flags doesn't get changed during parsing. Need to see if openjdk's implementation would allow that.

**Comment by courville** [comment]
Sorry for the lag in responding.
I do indeed run into:
```
024-04-24 18:54:11.476  6784-7128  com.archos...pRawLister org.courville.nova                   W  failure on (ActionInvocation) (Action, Arguments: 10) Browse response 500 Internal Server Error, Error: Error reading SOAP response message. Can't transform message payload (HTTP response was: 500 Internal Server Error)
2024-04-2
```
when playing different files in a row (first is ok though, or replaying it is ok too)...
I will check further when available.

**Comment by courville** [comment]
@norohind and @wborn, what would be the proper fix or workaround on Android?

**Comment by norohind** [comment]
I'm fine with this fix. Can we get this patch into jupnp? Should any of us open a PR or @wborn could just commit it, given he proposed this patch initially? 
Maybe also add to final patch reference to this issue in form of a comment as reason for this workaround wouldn't be obvious just looking at code.

**Comment by wborn** [comment]
Thanks for the feedback! I've created #235 for this.

**Comment by norohind** [comment]
Thanks for all work on the issue!

**Comment by courville** [comment]
@kaikreuzer, what about a new release tag pretty please?

**Comment by kaikreuzer** [comment]
Done! See https://github.com/jupnp/jupnp/releases/tag/3.0.2
