### ISSUE TITLE
UpnpService.getRegistry() is NULL

### ISSUE THREAD

**Issue by ZTMIDGO** [jupnp/jupnp#240]
```java
public class Main {

    public static void main(String[] args) throws Exception {
        UpnpService service = new UpnpServiceImpl(new DefaultUpnpServiceConfiguration());
        System.out.println(service.getRegistry());
        service.getRegistry().addDevice(createDevice());
    }

    public static org.jupnp.model.meta.LocalDevice createDevice() throws Exception {
        DeviceIdentity identity = new DeviceIdentity(UDN.uniqueSystemIdentifier("Demo Binary Light"));
        DeviceType type = new UDADeviceType("BinaryLight", 1);
        DeviceDetails details = new DeviceDetails("Friendly Binary Light", new ManufacturerDetails("ACME"), new ModelDetails("BinLight2000", "A demo light with on/off switch.", "v1"));

        LocalService<SwitchPower> switchPowerService = new AnnotationLocalServiceBinder().read(SwitchPower.class);
        switchPowerService.setManager(new DefaultServiceManager<>(switchPowerService, SwitchPower.class));

        return new LocalDevice(identity, type, details, new Icon[0], switchPowerService);
    }
}
```

<img width="527" alt="image" src="https://github.com/jupnp/jupnp/assets/50280785/50a4657e-09b7-4125-af14-3778caa8e931">

<img width="577" alt="image" src="https://github.com/jupnp/jupnp/assets/50280785/ffc4b13c-ad6c-4f5d-9543-8fc648b2d64d">

Get the same result on Android

implementation 'org.jupnp:org.jupnp:3.0.2'
implementation 'org.eclipse.jetty:jetty-server:8.1.21.v20160908'
implementation 'org.eclipse.jetty:jetty-servlet:8.1.21.v20160908'
implementation 'org.eclipse.jetty:jetty-client:8.1.21.v20160908'
implementation 'org.slf4j:slf4j-api:2.0.13'
implementation 'org.slf4j:slf4j-simple:2.0.13'

```java
public class DLNAService extends Service {

    @Override
    public void onCreate() {
        super.onCreate();
        UpnpService service = new UpnpServiceImpl();
        Log.e("TAG", "onCreate: "+service.getRegistry());
    }

    @Nullable
    @Override
    public IBinder onBind(Intent intent) {
        return null;
    }
}
```

**Comment by wborn** [comment]
Maybe it helps if you first call `upnpService.startup()` like in the [example](https://www.jupnp.org/docs/getting-started)?

**Comment by wborn** [comment]
No news is good news.

**Comment by lixingmao** [comment]
Android environment encounters the same issue, but AndroidUpnpService does not provide a startup() method.
Implementation method in [example for Android](https://www.jupnp.org/docs/android) still results in errors。
