### ISSUE TITLE
Missing "metadata-1.01-avt.xsd" makes AVTransportLastChangeParser always fail construction

### ISSUE THREAD

**Issue by haku** [jupnp/jupnp#245]
This issue can be reproduced with:
```
new org.jupnp.support.avtransport.lastchange.AVTransportLastChangeParser()
```

It is trying to load the classpath resource `"org/fourthline/cling/support/avtransport/metadata-1.01-avt.xsd"`, which appears to have gotten lost in the migration from cling to jupnp.
I can not find any .xsd files in the jupnp repo, so i suspect there are also some other missing resource files.

**Comment by wborn** [comment]
Hi @haku! I've created a fix for it in #247 maybe you can give it a test?
I saw a few more XSDs were missing as well.

**Comment by haku** [comment]
thanks for the fix!  works for me.

**Comment by kaikreuzer** [comment]
Good idea - here we go: https://github.com/jupnp/jupnp/releases/tag/3.0.3
