### ISSUE TITLE
Extend jupnptool for better configuration

### ISSUE THREAD

**Issue by JochenHiller** [jupnp/jupnp#31]
I would like to extend the command line tool "jupnptool" about this:
* use java.util.logging to slf4j bridge
* make logging smarter, especially for rejected tasks
* support configuration of thread pool (corePoolSize, maxPoolSize, queueSize)
* get better information how well does the thread pool is configured
* allow to specify the multicast port on commandline

I will provide a PR with these enhancements soon.

**Comment by kaikreuzer** [comment]
Implemented in https://github.com/jupnp/jupnp/pull/32
