### ISSUE TITLE
Migrate from java.util.logging to slf4j logging API?

### ISSUE THREAD

**Issue by JochenHiller** [jupnp/jupnp#37]
jUPnP uses (based on cling) java.util.logging as its primary logging API.
Some parts of jUPnP have yet been changed to use slf4j logging API.

Reading http://www.slf4j.org/legacy.html states:

NOTE ON PERFORMANCE Contrary to other bridging modules, namely jcl-over-slf4j and log4j-over-slf4j, which reimplement JCL and respectively log4j, the jul-to-slf4j module does not reimplement the java.util.logging because packages under the java.* namespace cannot be replaced. Instead, jul-to-slf4j translates LogRecord objects into their SLF4J equivalent. Please note this translation process incurs the cost of constructing a LogRecord instance regardless of whether the SLF4J logger is disabled for the given level or nor. Consequently, j.u.l. to SLF4J translation can seriously increase the cost of disabled logging statements (60 fold or 6000%) and measurably impact the performance of enabled log statements (20% overall increase). As of logback version 0.9.25, it is possible to completely eliminate the 60 fold translation overhead for disabled log statements with the help of LevelChangePropagator.

As maybe most users of jUPnP will use slf4j/logback/jul-slf4j bridge, shall we consider to change from java.util.logging completely to slf4j API?

**Comment by maggu2810** [comment]
:+1:

**Comment by JochenHiller** [comment]
I will start working on this issue

**Comment by kaikreuzer** [comment]
Cool, thanks!

**Comment by JochenHiller** [comment]
I have now the implementation running with slf4j only, and starting with testing now.

I changed the jUPnP implementation that way. Any feedback welcome.

* change Logger.getLogger(SomeClass.class.getName()) to LoggerFactory.getLogger(SomeClass.class)
* change log.fine to log.trace (293x)
* change log.finer to log.trace (134x)
* change log.finest to log.trace (15x)
* change log.sever to log.error (38x)
* change log.warning to log.warn (112x)
* change isLoggable(Level.FINE) to isTraceEnabled() (31x)
* change isLoggable(Level.FINER) to isTraceEnabled() (22x)
* change isLoggable(Level.FINEST) to isTraceEnabled() (10x)
* removed isTraceEnabled() as the trace() method will do same check, if only check for one single trace() statement
* changed log.log(Level.SEVERE to log.eror( (1x)
* changed log.log(Level.WARNING to log.warn( (7x)
* changed log.log(Level.INFO to log.info( (2x)
* changed log.log(Level.FINE to log.trace( (10x)
* changed log.log(Level.FINER to log.trace( (1x)
* check log.entering, change to log.trace("ENTRY {}.{}: {} {} {} {}", this.getClass().getName(), "", arg1, args2, arg3, arg4)
* removed all imports of java.util.logging.Level
* removed jul-over-slf4j bridge
* optimized all log.finest statements to log.trace but using {} placeholders for efficiency
* optimized some log messages where String.format was used to to use {} instead
* optimized imports for some classes, which may re-order import package statements

When finalized testing I will prepare a PR for that.

**Comment by JochenHiller** [comment]
I added now a PR with all changes: see https://github.com/jupnp/jupnp/pull/56
All test cases run successfully, I added logging when running tests and checked manually the generated log files for any errors.
I am yet missing re-testing of https://github.com/openhab/openhab-distro/issues/121 as this would require the Chromecast devices. But slf4j will allow easy configuration to NOT log to system console.

**Comment by maggu2810** [comment]
@JochenHiller I own two chromecast devices, but don't know at which time I can test (change residence).

**Comment by kaikreuzer** [comment]
I also have a chromecast and just tested the new build.
Unfortunately, https://github.com/openhab/openhab-distro/issues/121 does not seem to be solved by it -which is pretty weird and I have no further explanation where the hell this message to stdout could possibly come from...

**Comment by maggu2810** [comment]
I have created (some time ago) a Karaf console command to create a pom.xml that contains all the installed bundles in the dependencies section. If you load that project (directory that contains the pom) with e.g. Netbeans (not tested the Maven support of Eclipse for this approach) you could trigger a "download sources" of the project depenencies and start a remote debugging section.
With this steps I have all the source code that is running in the Karaf container and helped me a lot while debugging third party stuff.
If you are interested in that command, the bundle and a feature could be found in my kat repo.

**Comment by kaikreuzer** [comment]
Thanks @maggu2810, I will need some time to do debugging of https://github.com/openhab/openhab-distro/issues/121. I tend to simply have the project sources in the workspace and use the Eclipse remote debugging for that.

This issue can be closed as it has been implemented in https://github.com/jupnp/jupnp/pull/56 - thanks @JochenHiller!
