### ISSUE TITLE
Fix for hydrating Belkin Wemo Devices

### ISSUE THREAD

**Issue by hmerk** [jupnp/jupnp#42]
which is needed for the upcoming extension of ESH Wemo Binding.

This fix is running in my IDE for quite a long time now, without any impact on other bindings.

Best
Hans-Jörg

**Comment by hmerk** [comment]
@JochenHiller 
@kaikreuzer 
I just saw a post from Belkin in the WeMo forum as a reaction on my bug reports asking for my contact details to discuss this issues.
There might be a chance to get it all solved without needing to implement recovery methods.
Not knowing how long this could take, I would presume to merge the PR for now to move forward with the WeMo Binding.
Best
Hans-Jörg

**Comment by hmerk** [comment]
@JochenHiller , @kaikreuzer 
Solving the issues with Belkin will take longer, so we will need to implement the patches to move on with the new ESH binding version.
After discussing the issues with second level support I am now asked to adress those to the SDK team.
Best
Hans-Jörg

**Comment by kaikreuzer** [comment]
Implemented in https://github.com/jupnp/jupnp/pull/41
