### ISSUE TITLE
versioning scheme does not match the OSGi specifications

### ISSUE THREAD

**Issue by sjka** [jupnp/jupnp#53]
The composite update site includes those versions:
* 2.1.0
* 2.1.0.RC1

According to the OSGi spec ("Module Layer" -> "Resolving Metadata" -> "Bundle-Version"), the release candidate version is newer than the release version without a qualifier. Hence when resolving against the composite repository, the newest version won't be picked unless specified explicitly.

**Comment by kaikreuzer** [comment]
Sounds like a reason to remove the composite update site.

**Comment by kaikreuzer** [comment]
I have removed the RC from the composite repo (but kept it available under its own url), so this issue should be solved.
