### ISSUE TITLE
Maven repo: missing artifacts

### ISSUE THREAD

**Issue by maggu2810** [jupnp/jupnp#54]
Hello,
I want to use jUPnP in a maven project.

The org.jupnp POM refers to a parent that could not be found on e.g. jCenter (https://jcenter.bintray.com/org/jupnp/)
```xml
<parent>
    <groupId>org.jupnp.pom</groupId>
    <artifactId>bundles</artifactId>
    <version>2.1.0</version>
</parent>
```

```text
...
Downloading: https://jcenter.bintray.com/org/jupnp/pom/bundles/2.1.0/bundles-2.1.0.pom
Downloading: https://repo.maven.apache.org/maven2/org/jupnp/pom/bundles/2.1.0/bundles-2.1.0.pom
...
[ERROR] Failed to execute goal on project ...: Could not resolve dependencies for project ...: Failed to collect dependencies at org.jupnp:org.jupnp:jar:2.1.0: Failed to read artifact descriptor for org.jupnp:org.jupnp:jar:2.1.0: Could not find artifact org.jupnp.pom:bundles:pom:2.1.0 in ... -> [Help 1]
```

**Comment by maggu2810** [comment]
I have done it myself here https://github.com/maggu2810/mvn-repo/commit/354e2b412b4e4b33b7ea742efeff7c6c7ca78ed2 but I would prefer to have a correct version on jCenter.

**Comment by kaikreuzer** [comment]
All relevant parent poms should now be there:
https://bintray.com/jupnp/mvn/jUPnP/view#files/org/jupnp/jupnp/2.1.0
https://bintray.com/jupnp/mvn/jUPnP/view#files/org/jupnp/pom/bundles/2.1.0

Looks as if I should also cleanup the group ids of the different poms for the next release...
Please let me know, if this is resolved for you!

**Comment by maggu2810** [comment]
The artifacts are not available on jCenter. Perhaps we need some time if it is synced.
Using https://dl.bintray.com/jupnp/mvn/ as repo works.
