### ISSUE TITLE
Make jUPnP independent from apache http library

### ISSUE THREAD

**Issue by kaikreuzer** [jupnp/jupnp#70]
Currently, jUPnP [requires apache.http libs](https://github.com/jupnp/jupnp/blob/master/bundles/org.jupnp/META-INF/MANIFEST.MF#L20).
As these are quite large and might not be available on every system, it would be good to also work without them (using JDK internal classes) or at least with other http libs such as the Jetty client libs.

**Comment by ViToni** [comment]
First step in making the code agnostic about the transport implementation: PR https://github.com/jupnp/jupnp/pull/79

**Comment by ViToni** [comment]
There is a PR replacing Apache HTTP components with an uptodate Jetty implementation: https://github.com/jupnp/jupnp/pull/87
