### ISSUE TITLE
Maven Central

### ISSUE THREAD

**Issue by maggu2810** [jupnp/jupnp#76]
Any change to get released artifacts published on Maven Central?

**Comment by kaikreuzer** [comment]
I have requested it to be added: https://issues.sonatype.org/browse/OSSRH-28456

Not sure if the current 2.2.0 release fulfills all [requirements](http://central.sonatype.org/pages/requirements.html), though. So maybe we will only be able to push future releases to Maven Central.

**Comment by maggu2810** [comment]
Thank you!

**Comment by martinvw** [comment]
@kaikreuzer any updates about this?

**Comment by kaikreuzer** [comment]
Yes sure: Since version 2.3.0, it is available on Maven Central: https://mvnrepository.com/artifact/org.jupnp/jupnp

**Comment by maggu2810** [comment]
Hi Kai,
would it be possible to push 2.4.0 to Maven Central, too?

**Comment by kaikreuzer** [comment]
I thought I did, but I must have given up at that time.
Just checked and it still gives me "Last Sync Errors: Problem extracting files to sync. Please try again in a bit.".

Not sure what is wrong about it - will probably need some time to analyse the cause :-/

**Comment by kaikreuzer** [comment]
I have republished version 2.4.0 to Bintray and this time it now succeeded in pushing it out to Maven Central. Seems that something was broken with the previous artifacts on Bintray.

**Comment by maggu2810** [comment]
Thank you @kaikreuzer

**Comment by maggu2810** [comment]
It seems only the pom has been pushed: https://repo1.maven.org/maven2/org/jupnp/jupnp/2.4.0/

**Comment by kaikreuzer** [comment]
No, you have to look at the right place: http://central.maven.org/maven2/org/jupnp/org.jupnp/2.4.0/

**Comment by kaikreuzer** [comment]
And version 2.5.0 has now been published as well: http://central.maven.org/maven2/org/jupnp/org.jupnp/2.5.0/
