### ISSUE TITLE
ThreadPool rejected execution problem/excessive logging

### ISSUE THREAD

**Issue by kgoderis** [jupnp/jupnp#8]
When letting the ESH-embbedded jupnp loose on the network it does send out an UDP broadcast, then received back a lot of answers from a bunch of UPNP devices. It then sends out TCP requests to get service descriptors, with a lot of "200 OK" HTTP responses coming back, but then suddenly in the logs I see a massive amount of errors like these:

21:56:11.810 WARN  o.j.OSGiUpnpServiceConfiguration[:363]- Thread pool rejected execution of class org.jupnp.protocol.async.ReceivingSearchResponse

or 

21:56:12.004 WARN  o.j.OSGiUpnpServiceConfiguration[:363]- Thread pool rejected execution of class org.jupnp.protocol.async.ReceivingSearch

or 

21:56:12.696 WARN  o.j.OSGiUpnpServiceConfiguration[:363]- Thread pool rejected execution of class org.jupnp.protocol.RetrieveRemoteDescriptors

After a while I get a lof stuff like this (related to Sonos UPNP devices) : 

21:57:02.547 INFO  o.j.transport.spi.StreamClient[:87]- Timeout of 10 seconds while waiting for HTTP request to complete, aborting: (StreamRequestMessage) GET http://192.168.0.172:1400/xml/ZoneGroupTopology1.xml
21:57:02.547 INFO  o.j.transport.spi.StreamClient[:87]- Timeout of 10 seconds while waiting for HTTP request to complete, aborting: (StreamRequestMessage) GET http://192.168.0.151:1400/xml/GroupManagement1.xml
21:57:02.547 WARN  o.j.p.RetrieveRemoteDescriptors[:331]- Could not retrieve service descriptor, no response: (RemoteService) Descriptor: /xml/ZoneGroupTopology1.xml
21:57:02.548 WARN  o.j.p.RetrieveRemoteDescriptors[:331]- Could not retrieve service descriptor, no response: (RemoteService) Descriptor: /xml/GroupManagement1.xml
21:57:02.548 DEBUG o.j.p.RetrieveRemoteDescriptors[:327]- Sending service descriptor retrieval message: (StreamRequestMessage) GET http://192.168.0.172:1400/xml/GroupManagement1.xml
21:57:02.548 DEBUG o.j.p.RetrieveRemoteDescriptors[:327]- Sending service descriptor retrieval message: (StreamRequestMessage) GET http://192.168.0.151:1400/xml/QPlay1.xml
21:57:02.548 DEBUG org.jupnp.transport.Router[:329]- Sending via TCP unicast stream: (StreamRequestMessage) GET http://192.168.0.172:1400/xml/GroupManagement1.xml
21:57:02.548 DEBUG org.jupnp.transport.Router[:329]- Sending via TCP unicast stream: (StreamRequestMessage) GET http://192.168.0.151:1400/xml/QPlay1.xml
21:57:02.587 INFO  o.j.transport.spi.StreamClient[:87]- Timeout of 10 seconds while waiting for HTTP request to complete, aborting: (StreamRequestMessage) GET http://192.168.0.173:1400/xml/HTControl1.xml
21:57:02.587 WARN  o.j.p.RetrieveRemoteDescriptors[:331]- Could not retrieve service descriptor, no response: (RemoteService) Descriptor: /xml/HTControl1.xml
21:57:02.587 DEBUG o.j.p.RetrieveRemoteDescriptors[:327]- Sending service descriptor retrieval message: (StreamRequestMessage) GET http://192.168.0.173:1400/xml/QPlay1.xml
21:57:02.587 DEBUG org.jupnp.transport.Router[:329]- Sending via TCP unicast stream: (StreamRequestMessage) GET http://192.168.0.173:1400/xml/QPlay1.xml
21:57:02.610 INFO  o.j.transport.spi.StreamClient[:87]- Timeout of 10 seconds while waiting for HTTP request to complete, aborting: (StreamRequestMessage) GET http://192.168.0.171:1400/xml/ZoneGroupTopology1.xml

**Comment by kaikreuzer** [comment]
This should be fixed with https://github.com/jupnp/jupnp/pull/47

**Comment by tenevo** [comment]
Hello @kaikreuzer ,
could you please apply the Same change in the Class DefaultUpnpServiceConfiguration on the method createDefaultExecutorService(). The Method has still an old implementation and is blocking due to the use of ArrayBlockingQueue.

Making use of the following implementation should resolve the problem, i think.
`protected ExecutorService createDefaultExecutorService() {
	return QueueingThreadPoolExecutor.createInstance("upnp-async", 200);
}`

And the internal class JUPnPExecutor should be remove.
Thanks in advance.

**Comment by kaikreuzer** [comment]
@tenevo Could you please open a new issue for this? Any reason why you do not create a PR yourself?

**Comment by tenevo** [comment]
@kaikreuzer , I did it. 
Thanks for Review.
