### ISSUE TITLE
Major problems with library version 2.3

### ISSUE THREAD

**Issue by lolodomo** [jupnp/jupnp#88]
New version 2.3 of the library has broken the Eclipse Smarthome Sonos binding.
It looks like sometimes device.findService returns null and when it does not, service.getAction returns null.
The behaviour is random.

The ESH binding is working perfectly with library version 2.2.

ESH issue: https://github.com/eclipse/smarthome/issues/4531

**Comment by kaikreuzer** [comment]
Sorry, this is far too fuzzy, nobody can fix anything with that description.
Please let us open an issue only as soon as one has been clearly identified and can be described.

**Comment by lolodomo** [comment]
This is a joke ?
How can I describe something that looks like partially random.
There is a problem, that is just obvious, we are several to mention it.
I have done my max to show that the problem is in this library.
